// import { ReduxProvider } from '@/store/provider'
// import { TanstackProvider } from '@/providers/TanstackProvider';
import '@/styles/globals.scss'

import type { Metadata } from 'next'
import '@/styles/layout.scss'
import { AppLayout } from '@/services/exports';
import NextUiProvider from '@/providers/NextUIProvider';
import { UserProvider } from '@/providers/UserContextProvider';
import { ReduxProvider } from '@/store/provider';
export const metadata: Metadata = {
  title: 'Shiftable App',
  description: 'Generated by Shaked Golan',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en" className='h-full' suppressHydrationWarning>
      <body className={`h-full bg-bgc-light dark:bg-bgc-dark`}>
      <NextUiProvider>
        {/* <TanstackProvider> */}
          <UserProvider>
          <ReduxProvider>
              <AppLayout children={children} />
          </ReduxProvider>
          </UserProvider>
        {/* </TanstackProvider> */}
          </NextUiProvider>
     
    </body>
    </html>
  )
}

// If want store - uncomment the ReduxProvider
