// import { ReduxProvider } from '@/store/provider'
import { TanstackProvider } from '@/components/TanstackProvider';
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })
import { QueryClient, QueryClientProvider } from "react-query";
import { UserProvider } from '@/components/UserContextProvider';

export const metadata: Metadata = {
  title: 'Shiftable App',
  description: 'Generated by Shaked Golan',
}



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {



  return (

    <html lang="en" className='h-full bg-white'>
      <body className={inter.className + ` h-full`}>
        <TanstackProvider>
          <UserProvider>
            {/* <ReduxProvider> */}
            {children}
            {/* </ReduxProvider> */}
          </UserProvider>
        </TanstackProvider>
      </body>
    </html>

  )
}

// If want store - uncomment the ReduxProvider
